# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Raw\app_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_header = QtWidgets.QLabel(self.centralwidget)
        self.label_header.setObjectName("label_header")
        self.gridLayout.addWidget(self.label_header, 0, 0, 1, 1)
        self.pushButton_save = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_save.setObjectName("pushButton_save")
        self.gridLayout.addWidget(self.pushButton_save, 3, 2, 1, 1)
        self.tableWidget_problems = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_problems.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_problems.setObjectName("tableWidget_problems")
        self.tableWidget_problems.setColumnCount(0)
        self.tableWidget_problems.setRowCount(0)
        self.tableWidget_problems.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidget_problems.horizontalHeader().setMinimumSectionSize(50)
        self.tableWidget_problems.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.tableWidget_problems, 1, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        self.label_complete_def = QtWidgets.QLabel(self.centralwidget)
        self.label_complete_def.setMinimumSize(QtCore.QSize(0, 45))
        self.label_complete_def.setText("")
        self.label_complete_def.setObjectName("label_complete_def")
        self.gridLayout.addWidget(self.label_complete_def, 2, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_Sheet = QtWidgets.QAction(MainWindow)
        self.actionLoad_Sheet.setObjectName("actionLoad_Sheet")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionShow_Pending_Problems = QtWidgets.QAction(MainWindow)
        self.actionShow_Pending_Problems.setObjectName("actionShow_Pending_Problems")
        self.actionShow_Completed_Problems = QtWidgets.QAction(MainWindow)
        self.actionShow_Completed_Problems.setObjectName("actionShow_Completed_Problems")
        self.menuFile.addAction(self.actionLoad_Sheet)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionShow_Pending_Problems)
        self.menuFile.addAction(self.actionShow_Completed_Problems)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DSA PROBLEM TRACKER"))
        self.label_header.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:600; text-decoration: underline;\">DSA CRACKER SHEET</span></p></body></html>"))
        self.pushButton_save.setText(_translate("MainWindow", "Save Changes"))
        self.pushButton_save.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionLoad_Sheet.setText(_translate("MainWindow", "Load Sheet"))
        self.actionLoad_Sheet.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As"))
        self.actionSave_As.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.actionShow_Pending_Problems.setText(_translate("MainWindow", "Show Pending Problems"))
        self.actionShow_Pending_Problems.setShortcut(_translate("MainWindow", "Ctrl+1"))
        self.actionShow_Completed_Problems.setText(_translate("MainWindow", "Show Completed Problems"))
        self.actionShow_Completed_Problems.setShortcut(_translate("MainWindow", "Ctrl+2"))
