# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Raw\new_problems_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os

BASE = os.path.dirname(__file__)
class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(748, 381)
        Dialog.setStyleSheet("QLineEdit{\n"
"    border: 0px solid white;\n"
"    border-radius: 5px;\n"
"    padding: 3px;\n"
"}\n"
"QLineEdit[readOnly=\"true\"]{\n"
"    background-color: rgb(208, 208, 208);\n"
"    border: 0px solid white;\n"
"    border-radius: 5px;\n"
"    padding: 3px;\n"
"}\n"
"#Dialog{\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0.535, x2:1, y2:0.494682, stop:0 rgba(255, 156, 35, 255), stop:0.551136 rgba(255, 170, "
                             "0, 255), stop:1 rgba(255, 85, 0, 255));\n "
"}\n"
"QLabel{\n"
"background-color: rgba(198, 198, 198, 150);\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_save = QtWidgets.QPushButton(Dialog)
        self.pushButton_save.setStyleSheet("#pushButton_save{\n"
"padding: 3px;\n"
"margin: 5px 5px;\n"
"border: 1px solid grey;\n"
"background-color: rgb(105, 105, 158);\n"
"border-radius: 5px\n"
"}\n"
"#pushButton_save:pressed{\n"
"padding: 3px;\n"
"margin: 5px 5px;\n"
"border: 1px solid grey;\n"
"    background-color: rgb(51, 51, 77);\n"
"border-radius: 5px\n"
"}")
        self.pushButton_save.setObjectName("pushButton_save")
        self.horizontalLayout_5.addWidget(self.pushButton_save)
        self.pushButton_cancel = QtWidgets.QPushButton(Dialog)
        self.pushButton_cancel.setStyleSheet("#pushButton_cancel{\n"
"padding: 3px;\n"
"margin: 5px 5px;\n"
"border: 1px solid grey;\n"
"    background-color: rgb(255, 45, 30);\n"
"border-radius: 5px\n"
"}\n"
"#pushButton_cancel:pressed{\n"
"padding: 3px;\n"
"margin: 5px 5px;\n"
"border: 1px solid grey;\n"
"    background-color: rgb(166, 9, 9);\n"
"border-radius: 5px\n"
"}")
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout_5.addWidget(self.pushButton_cancel)
        self.gridLayout.addLayout(self.horizontalLayout_5, 3, 2, 1, 1)
        self.label_header = QtWidgets.QLabel(Dialog)
        self.label_header.setStyleSheet("#label_header{\n"
"    background-color:    rgba(197, 197, 197, 150);\n"
"    border: 1px solid grey;\n"
"    border-radius: 5px 5px;\n"
"    padding: 5px;\n"
"}")
        self.label_header.setTextFormat(QtCore.Qt.RichText)
        self.label_header.setAlignment(QtCore.Qt.AlignCenter)
        self.label_header.setObjectName("label_header")
        self.gridLayout.addWidget(self.label_header, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_probId = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_probId.setReadOnly(True)
        self.lineEdit_probId.setObjectName("lineEdit_probId")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_probId)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lineEdit_name = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_name)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.lineEdit_link = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_link.setObjectName("lineEdit_link")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_link)
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.lineEdit_topic = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_topic.setObjectName("lineEdit_topic")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_topic)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.gridLayout.addLayout(self.formLayout, 2, 0, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_save.setText(_translate("Dialog", "Save"))
        self.pushButton_cancel.setText(_translate("Dialog", "Cancel"))

        img_path = os.path.realpath(os.path.join(BASE, "../images/point_down.jpg"))
        self.label_header.setText(_translate("Dialog", f"<html><head/><body><p><img src=\"{img_path}\" width=\"150\"/></p><p>Add New Problems "
                                                       "Here!</p></body></html>"))
        self.label_2.setText(_translate("Dialog", "Problem ID:"))
        self.label_6.setText(_translate("Dialog", "Problem Name:"))
        self.label_7.setText(_translate("Dialog", "Source Link:"))
        self.label_8.setText(_translate("Dialog", "Is Done?"))
        self.comboBox.setItemText(0, _translate("Dialog", "No"))
        self.comboBox.setItemText(1, _translate("Dialog", "Yes"))
        self.label.setText(_translate("Dialog", "Topic:"))
